-- GENERATED by tools/gen-geo.py from docs/maquettes/v2/assets/geometry.json
-- Do not hand edit. The maquette geometry is the single source of truth.
-- PZ's require() does not capture module returns, so this hangs off the
-- mod's own global table, like every other WeightScale module.
WeightScale = WeightScale or {}
WeightScale.Geo = WeightScale.Geo or {}
local WeightScaleGeo = WeightScale.Geo

WeightScaleGeo.weight = { min = 35.0, max = 130.0, start = 80.0 }

WeightScaleGeo.bands = {
    { id = 'emaciated', upTo = 50.0, inc = true, colour = {138, 58, 52} },
    { id = 'tresMaigre', upTo = 65.0, inc = true, colour = {152, 96, 46} },
    { id = 'maigre', upTo = 75.0, inc = false, colour = {146, 132, 58} },
    { id = 'normal', upTo = 85.0, inc = false, colour = {104, 142, 78} },
    { id = 'surpoids', upTo = 100.0, inc = false, colour = {146, 132, 58} },
    { id = 'obese', upTo = 130.0, inc = true, colour = {148, 72, 50} },
}

WeightScaleGeo.readout = { w = 288, h = 132 }
WeightScaleGeo.poise = { w = 16, h = 30 }
WeightScaleGeo.slab = { x = 0, y = 88, w = 288, h = 44 }
WeightScaleGeo.track = { x0 = 30, w = 218, tickBaseY = 38, minorH = 6, majorH = 12,
  bandY = 40, bandH = 5, majorEvery = 25, minorEvery = 5 }
WeightScaleGeo.beam = { pivotX = 18, pivotY = 65, len = 248, h = 12, maxDeg = 1.9 }
WeightScaleGeo.stops = { x = 250, w = 18, gap = 9 }
WeightScaleGeo.offset = { dx = 150, dy = -230 }
WeightScaleGeo.panel = { w = 152, h = 52, dx = 150, dy = -170 }
