#!/usr/bin/env python3
"""Bake the beam-head textures. Every look (grain, bevel, wear, soil) is baked
into the PNG, so the draw side only needs drawTexture / drawTextureScaled and
one rotated draw for the beam."""
import json, os
from PIL import Image, ImageDraw
import tex

HERE = os.path.dirname(os.path.abspath(__file__))
G = json.load(open(os.path.join(HERE, "geometry.json")))

ENAMEL_TOP = (226, 219, 200)
ENAMEL_BOT = (188, 180, 160)
BEAM_TOP = (60, 60, 68)
BEAM_BOT = (22, 22, 27)
SLAB_TOP = (40, 40, 43)
SLAB_BOT = (22, 22, 25)


def plate():
    p, r = G["plate"], G["recess"]
    im = tex.surface(p["w"], p["h"], ENAMEL_TOP, ENAMEL_BOT)
    tex.grain(im, 6, 0.6)
    tex.soil(im, 26)
    tex.bevel(im)
    tex.rim(im, (34, 32, 26, 235))
    d = ImageDraw.Draw(im, "RGBA")
    # recessed channel the beam swings in: darker, with its own inverted bevel
    d.rectangle([r["x"], r["y"], r["x"] + r["w"] - 1, r["y"] + r["h"] - 1],
                fill=(11, 11, 12, 255))
    d.line([(r["x"], r["y"]), (r["x"] + r["w"] - 1, r["y"])], fill=(14, 13, 12, 255))
    d.line([(r["x"], r["y"] + r["h"] - 1), (r["x"] + r["w"] - 1, r["y"] + r["h"] - 1)],
           fill=(150, 144, 128, 90))
    # two fixing screws, top corners
    for sx in (9, p["w"] - 10):
        d.ellipse([sx - 3, 7, sx + 3, 13], fill=(150, 144, 126, 255),
                  outline=(70, 66, 54, 255))
        d.line([(sx - 2, 10), (sx + 2, 10)], fill=(70, 66, 54, 255))
    tex.wear(im, 11, (248, 245, 236, 110))
    tex.wear(im, 12, (104, 96, 76, 120))
    im.save(os.path.join(HERE, "plate.png"))


def beam():
    b = G["beam"]
    im = tex.surface(b["len"], b["h"], BEAM_TOP, BEAM_BOT)
    tex.grain(im, 5, 0.5)
    d = ImageDraw.Draw(im, "RGBA")
    d.line([(0, 0), (b["len"] - 1, 0)], fill=(138, 138, 150, 235))
    d.line([(0, b["h"] - 1), (b["len"] - 1, b["h"] - 1)], fill=(8, 8, 9, 255))
    # rider groove the poise sits in
    d.rectangle([6, 4, b["len"] - 7, 6], fill=(12, 12, 14, 255))
    d.line([(6, 7), (b["len"] - 7, 7)], fill=(104, 104, 114, 170))
    # the knuckle at the pivot end: it turns with the beam, so it lives here
    d.ellipse([1, 0, 11, b["h"] - 1], fill=(188, 182, 164, 255),
              outline=(30, 28, 24, 255))
    d.ellipse([5, 4, 7, 7], fill=(44, 42, 36, 255))
    tex.wear(im, 9, (132, 130, 122, 85), along="all")
    im.save(os.path.join(HERE, "beam.png"))


def poise():
    p = G["poise"]
    im = Image.new("RGBA", (p["w"], p["h"]), (0, 0, 0, 0))
    d = ImageDraw.Draw(im, "RGBA")
    body = [(2, 6), (p["w"] - 3, 6), (p["w"] - 5, p["h"] - 2), (4, p["h"] - 2)]
    d.polygon(body, fill=(166, 160, 142, 255), outline=(52, 48, 40, 255))
    d.polygon([(p["w"] // 2, 0), (p["w"] // 2 + 3, 6), (p["w"] // 2 - 3, 6)],
              fill=(214, 208, 188, 255), outline=(52, 48, 40, 255))
    d.line([(4, 7), (p["w"] - 5, 7)], fill=(222, 216, 196, 255))
    d.line([(5, p["h"] - 3), (p["w"] - 6, p["h"] - 3)], fill=(74, 70, 58, 255))
    d.rectangle([p["w"] // 2 - 1, 11, p["w"] // 2, p["h"] - 6], fill=(96, 92, 78, 255))
    tex.grain(im, 8, 0.45)
    im.save(os.path.join(HERE, "poise.png"))


def stops():
    s = G["stops"]
    im = tex.surface(s["w"], s["h"], ENAMEL_TOP, ENAMEL_BOT)
    tex.grain(im, 6, 0.5)
    d = ImageDraw.Draw(im, "RGBA")
    d.rectangle([5, 6, s["w"] - 6, s["h"] - 7], fill=(0, 0, 0, 0))
    for y in (10, s["h"] - 12):  # the two stops the beam tip floats between
        d.rectangle([6, y, s["w"] - 7, y + 1], fill=(196, 190, 170, 255))
    tex.bevel(im)
    tex.rim(im, (34, 32, 26, 235))
    tex.wear(im, 6, (248, 245, 236, 120))
    im.save(os.path.join(HERE, "stops.png"))


def slab():
    s = G["slab"]
    im = tex.surface(s["w"], s["h"], SLAB_TOP, SLAB_BOT)
    tex.grain(im, 5, 0.55)
    tex.soil(im, 14, (96, 90, 74), (6, 14))
    d = ImageDraw.Draw(im, "RGBA")
    d.line([(0, 0), (s["w"] - 1, 0)], fill=(126, 122, 110, 210))
    d.line([(0, s["h"] - 1), (s["w"] - 1, s["h"] - 1)], fill=(8, 8, 9, 255))
    for rx in (7, s["w"] - 8):
        d.ellipse([rx - 2, 5, rx + 2, 9], fill=(120, 116, 102, 255),
                  outline=(16, 16, 18, 255))
    tex.rim(im, (12, 12, 13, 235))
    im.save(os.path.join(HERE, "slab.png"))


def geo_js():
    out = "// generated by build_textures.py, do not edit\nwindow.WS_GEO = "
    out += json.dumps(G, indent=1) + ";\n"
    open(os.path.join(HERE, "..", "js", "geo.js"), "w").write(out)


if __name__ == "__main__":
    plate(); beam(); poise(); slab(); geo_js()
    print("textures baked in", HERE)
