#!/usr/bin/env python3
"""Generates src/lua/client/WeightScale/WeightScaleGeo.lua from the maquette's
geometry.json. Geometry, bands and thresholds have exactly one source: the
approved maquette. Never hand edit the generated file, edit geometry.json (or
the maquette contract) and rerun this script.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_JSON = os.path.join(ROOT, "docs", "maquettes", "v2", "assets", "geometry.json")
OUT_LUA = os.path.join(ROOT, "src", "lua", "client", "WeightScale", "WeightScaleGeo.lua")


def lua_bool(v):
    return "true" if v else "false"


def gen_bands(bands):
    lines = []
    for b in bands:
        lines.append(
            "    { id = %r, upTo = %s, inc = %s, colour = {%d, %d, %d} },"
            % (b["id"], b["upTo"], lua_bool(b["inc"]), b["colour"][0], b["colour"][1], b["colour"][2])
        )
    return "\n".join(lines)


def build(g):
    out = []
    out.append("-- GENERATED by tools/gen-geo.py from docs/maquettes/v2/assets/geometry.json")
    out.append("-- Do not hand edit. The maquette geometry is the single source of truth.")
    out.append("-- PZ's require() does not capture module returns, so this hangs off the")
    out.append("-- mod's own global table, like every other WeightScale module.")
    out.append("WeightScale = WeightScale or {}")
    out.append("WeightScale.Geo = WeightScale.Geo or {}")
    out.append("local WeightScaleGeo = WeightScale.Geo")
    out.append("")
    out.append("WeightScaleGeo.weight = { min = %s, max = %s, start = %s }" % (
        g["weight"]["min"], g["weight"]["max"], g["weight"]["start"]))
    out.append("WeightScaleGeo.weightDigital = { min = %s, max = %s, start = %s }" % (
        g["weightDigital"]["min"], g["weightDigital"]["max"], g["weightDigital"]["start"]))
    out.append("")
    out.append("WeightScaleGeo.bands = {")
    out.append(gen_bands(g["bands"]))
    out.append("}")
    out.append("")
    for key in ("readout", "poise", "slab"):
        v = g[key]
        parts = ", ".join("%s = %s" % (k, v[k]) for k in v)
        out.append("WeightScaleGeo.%s = { %s }" % (key, parts))
    t = g["track"]
    out.append("WeightScaleGeo.track = { x0 = %s, w = %s, tickBaseY = %s, minorH = %s, majorH = %s,"
                % (t["x0"], t["w"], t["tickBaseY"], t["minorH"], t["majorH"]))
    out.append("  bandY = %s, bandH = %s, majorEvery = %s, minorEvery = %s }"
                % (t["bandY"], t["bandH"], t["majorEvery"], t["minorEvery"]))
    b = g["beam"]
    out.append("WeightScaleGeo.beam = { pivotX = %s, pivotY = %s, len = %s, h = %s, maxDeg = %s }"
                % (b["pivotX"], b["pivotY"], b["len"], b["h"], b["maxDeg"]))
    s = g["stops"]
    out.append("WeightScaleGeo.stops = { x = %s, w = %s, gap = %s }"
                % (s["x"], s["w"], s["gap"]))
    o = g["offset"]
    out.append("WeightScaleGeo.offset = { dx = %s, dy = %s }" % (o["dx"], o["dy"]))
    p = g["panel"]
    out.append("WeightScaleGeo.panel = { w = %s, h = %s, dx = %s, dy = %s }" % (p["w"], p["h"], p["dx"], p["dy"]))
    out.append("")
    return "\n".join(out)


def main():
    check = "--check" in sys.argv
    with open(SRC_JSON) as f:
        g = json.load(f)
    text = build(g)

    if check:
        current = ""
        if os.path.exists(OUT_LUA):
            with open(OUT_LUA) as f:
                current = f.read()
        if current != text:
            print("DRIFT: " + OUT_LUA + " does not match geometry.json (rerun without --check)", file=sys.stderr)
            return 1
        print("OK: " + OUT_LUA + " matches geometry.json")
        return 0

    os.makedirs(os.path.dirname(OUT_LUA), exist_ok=True)
    with open(OUT_LUA, "w") as f:
        f.write(text)
    print("wrote " + OUT_LUA)
    return 0


if __name__ == "__main__":
    sys.exit(main())
